replicaCount: 1

image:
  repository: ghcr.io/ekucher
  tag: v1.0.0-934a392-linux
  arch: amd64
  pullPolicy: IfNotPresent

telegram:
  secretName: kbot-secret
  secretKey: TELE_TOKEN

observability:
  otlpEndpoint: "http://kbot-collector.observability.svc.cluster.local:4317"
  environment: "dev"
